=head1 NAME

NCarton::Doc::Exec - execute your script in a cartone local environment

=head1 SYNOPSIS

  cartone exec perl myscript.pl

=head1 DESCRIPTION

This command allows you to run your script in an isolated cartone local
environment, which means the perl 5 library path C<@INC> are the only
ones from perl's core library path, cartone's library path
(i.e. C<local/lib/perl5>) and the current directory.

This is useful to make sure your scripts and application use the exact
same versions of the modules in your library path, and are not using
any of the modules you accidentally installed into your system perl or
perlbrew's site library path.
